name: Quality Checks

on:
    push:
        branches:
            - '*'

jobs:
    quality-checks:
        name: 'Run Quality Checks'
        uses: 'AyoubNafil/NadActions/.github/workflows/quality-checks.yml@main'
